<a href="https://colab.research.google.com/github/durgeshchavan25-svg/Data_Science_Lab/blob/main/practical_no_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a) Create a 3x3 square matrix and compute its determinant.

In [16]:
import numpy as np

# Taking user input for the 3x3 matrix
print("Enter elements of the 3x3 matrix:")

matrix = []
for i in range(3):
    row = []
    for j in range(3):
        value = float(input(f"Enter element at position ({i+1},{j+1}): "))
        row.append(value)
    matrix.append(row)

# Convert to NumPy array
matrix = np.array(matrix)

# Calculate determinant
determinant = np.linalg.det(matrix)

# Display matrix and determinant (rounded to 2 decimal places)
print("\nMatrix:")
print(matrix)

print("\nDeterminant of the matrix = {:.2f}".format(determinant))


Enter elements of the 3x3 matrix:
Enter element at position (1,1): 3
Enter element at position (1,2): 4
Enter element at position (1,3): 5
Enter element at position (2,1): 3
Enter element at position (2,2): 3
Enter element at position (2,3): 4
Enter element at position (3,1): 5
Enter element at position (3,2): 5
Enter element at position (3,3): 4

Matrix:
[[3. 4. 5.]
 [3. 3. 4.]
 [5. 5. 4.]]

Determinant of the matrix = 8.00


a) Create a 3x3 square matrix and compute its determinant without using function.

In [17]:
# Taking input for the 3x3 matrix
print("Enter elements of the 3x3 matrix:")

matrix = []
for i in range(3):
    row = []
    for j in range(3):
        value = int(input(f"Enter element at position ({i+1},{j+1}): "))
        row.append(value)
    matrix.append(row)

# Assign matrix elements
a = matrix[0][0]
b = matrix[0][1]
c = matrix[0][2]

d = matrix[1][0]
e = matrix[1][1]
f = matrix[1][2]

g = matrix[2][0]
h = matrix[2][1]
i = matrix[2][2]

# Determinant calculation
determinant = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

# Display result
print("\nMatrix:")
for row in matrix:
    print(row)

print("\nDeterminant of the matrix =", determinant)



Enter elements of the 3x3 matrix:
Enter element at position (1,1): 3
Enter element at position (1,2): 4
Enter element at position (1,3): 5
Enter element at position (2,1): 3
Enter element at position (2,2): 3
Enter element at position (2,3): 4
Enter element at position (3,1): 5
Enter element at position (3,2): 5
Enter element at position (3,3): 4

Matrix:
[3, 4, 5]
[3, 3, 4]
[5, 5, 4]

Determinant of the matrix = 8


b) Find the inverse of the matrix.

In [18]:
import numpy as np

# Taking user input for the 3x3 matrix
print("Enter elements of the 3x3 matrix:")

matrix = []
for i in range(3):
    row = []
    for j in range(3):
        value = float(input(f"Enter element at position ({i+1},{j+1}): "))
        row.append(value)
    matrix.append(row)

# Convert list to NumPy array
matrix = np.array(matrix)

print("\nMatrix:")
print(matrix)

# Check determinant and find inverse
determinant = np.linalg.det(matrix)

if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
else:
    print("\nInverse does not exist (Determinant = 0)")


Enter elements of the 3x3 matrix:
Enter element at position (1,1): 2
Enter element at position (1,2): 3
Enter element at position (1,3): 4
Enter element at position (2,1): 1
Enter element at position (2,2): 5
Enter element at position (2,3): 6
Enter element at position (3,1): 7
Enter element at position (3,2): 4
Enter element at position (3,3): 3

Matrix:
[[2. 3. 4.]
 [1. 5. 6.]
 [7. 4. 3.]]

Inverse of the matrix:
[[ 0.36 -0.28  0.08]
 [-1.56  0.88  0.32]
 [ 1.24 -0.52 -0.28]]




b) Find the inverse of the matrix without using function.


In [20]:
3
# Taking input for the 3x3 matrix
print("Enter elements of the 3x3 matrix:")

matrix = []
for i in range(3):
    row = []
    for j in range(3):
        value = float(input(f"Enter element at position ({i+1},{j+1}): "))
        row.append(value)
    matrix.append(row)

# Assign elements
a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

# Determinant
determinant = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

if determinant == 0:
    print("\nInverse does not exist (Determinant = 0)")
else:
    # Cofactor matrix
    cofactor = [
        [(e*i - f*h), -(d*i - f*g), (d*h - e*g)],
        [-(b*i - c*h), (a*i - c*g), -(a*h - b*g)],
        [(b*f - c*e), -(a*f - c*d), (a*e - b*d)]
    ]

    # Transpose of cofactor (Adjoint)
    adjoint = [
        [cofactor[0][0], cofactor[1][0], cofactor[2][0]],
        [cofactor[0][1], cofactor[1][1], cofactor[2][1]],
        [cofactor[0][2], cofactor[1][2], cofactor[2][2]]
    ]

    # Inverse matrix
    inverse = [
        [adjoint[r][c] / determinant for c in range(3)]
        for r in range(3)
    ]

    print("\nInverse of the matrix:")
    for row in inverse:
        print(row)


Enter elements of the 3x3 matrix:
Enter element at position (1,1): 2
Enter element at position (1,2): 3
Enter element at position (1,3): 4
Enter element at position (2,1): 1
Enter element at position (2,2): 5
Enter element at position (2,3): 6
Enter element at position (3,1): 7
Enter element at position (3,2): 4
Enter element at position (3,3): 3

Inverse of the matrix:
[0.36, -0.28, 0.08]
[-1.56, 0.88, 0.32]
[1.24, -0.52, -0.28]


c) Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20

In [23]:
import numpy as np

print("Solve the system of linear equations:")
print("Equation 1: a1*x + b1*y = c1")
print("Equation 2: a2*x + b2*y = c2\n")

# Input coefficients from the user
a1 = float(input("Enter coefficient a1 (for x in eq1): "))
b1 = float(input("Enter coefficient b1 (for y in eq1): "))
c1 = float(input("Enter constant c1 (for eq1): "))

a2 = float(input("Enter coefficient a2 (for x in eq2): "))
b2 = float(input("Enter coefficient b2 (for y in eq2): "))
c2 = float(input("Enter constant c2 (for eq2): "))

# Coefficient matrix A
A = np.array([[a1, b1],
              [a2, b2]])

# Constants vector B
B = np.array([c1, c2])

# Check determinant to see if system has a unique solution
determinant = np.linalg.det(A)

if determinant == 0:
    print("\nThe system has no unique solution (Determinant = 0).")
else:
    # Solve the system
    solution = np.linalg.solve(A, B)
    print("\nSolution of the system:")
    print("x = {:.2f}".format(solution[0]))
    print("y = {:.2f}".format(solution[1]))


Solve the system of linear equations:
Equation 1: a1*x + b1*y = c1
Equation 2: a2*x + b2*y = c2

Enter coefficient a1 (for x in eq1): 2
Enter coefficient b1 (for y in eq1): 3
Enter constant c1 (for eq1): 10
Enter coefficient a2 (for x in eq2): 4
Enter coefficient b2 (for y in eq2): 5
Enter constant c2 (for eq2): 20

Solution of the system:
x = 5.00
y = 0.00


c) Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20,without using the function

In [24]:
print("Solve the system of linear equations:")
print("Equation 1: a1*x + b1*y = c1")
print("Equation 2: a2*x + b2*y = c2\n")

# Input coefficients from the user
a1 = float(input("Enter coefficient a1 (for x in eq1): "))
b1 = float(input("Enter coefficient b1 (for y in eq1): "))
c1 = float(input("Enter constant c1 (for eq1): "))

a2 = float(input("Enter coefficient a2 (for x in eq2): "))
b2 = float(input("Enter coefficient b2 (for y in eq2): "))
c2 = float(input("Enter constant c2 (for eq2): "))

# Determinant of the coefficient matrix
D = a1*b2 - a2*b1

if D == 0:
    print("\nThe system has no unique solution (Determinant = 0).")
else:
    # Cramer's Rule
    Dx = c1*b2 - c2*b1
    Dy = a1*c2 - a2*c1

    x = Dx / D
    y = Dy / D

    print("\nSolution of the system:")
    print("x = {:.2f}".format(x))
    print("y = {:.2f}".format(y))


Solve the system of linear equations:
Equation 1: a1*x + b1*y = c1
Equation 2: a2*x + b2*y = c2

Enter coefficient a1 (for x in eq1): 2
Enter coefficient b1 (for y in eq1): 3
Enter constant c1 (for eq1): 10
Enter coefficient a2 (for x in eq2): 4
Enter coefficient b2 (for y in eq2): 5
Enter constant c2 (for eq2): 20

Solution of the system:
x = 5.00
y = -0.00
